apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular
  name: angular
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
      name: angular
    spec:
      containers:
      - image: spurthiaddagada/swe645frontimage:v1
        imagePullPolicy: Always
        name: angular
